# Generated by Django 4.2.11 on 2024-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='react',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
