# Generated by Django 4.2.11 on 2024-06-16 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0024_remove_studio_country_anime_country'),
        ('user', '0003_viewedepisode_viewedanime_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FAVORITE', 'Favorite'), ('VIEWED', 'Viewed'), ('DROPPED', 'Dropped'), ('PLANNED', 'Planned'), ('WATCHING', 'Watching')])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewedanime',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='viewedanime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewedepisode',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='viewedepisode',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='ViewedAnime',
        ),
        migrations.DeleteModel(
            name='ViewedEpisode',
        ),
    ]
