# Generated by Django 4.2.11 on 2024-08-12 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useranime_remove_viewedanime_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranime',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='action',
            field=models.CharField(choices=[('FAVORITE', 'Улюблені'), ('VIEWED', 'Переглянуті'), ('DROPPED', 'Кинуті'), ('PLANNED', 'Заплановані'), ('WATCHING', 'Дивлюся зараз')]),
        ),
    ]
