# Generated by Django 4.2.11 on 2024-09-03 13:45

import apps.anime.s3_path
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date and time')),
                ('title', models.CharField(db_index=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('SERIAL', 'Серіал'), ('FILM', 'Фільм'), ('ONA', 'ONA'), ('OVA', 'OVA')], max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CAME_OUT', 'Вийшов'), ('COMES_OUT', 'Виходить'), ('ANNOUNCED', 'Анонсовано')], default='ANNOUNCED', max_length=255)),
                ('rating', models.CharField(choices=[('G', 'All Ages'), ('PG', 'Children'), ('PG13', 'Teens 13 and Older'), ('R', '(violence & profanity)'), ('RPLUS', 'Profanity & Mild Nudity')], max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(default='', max_length=255)),
                ('season', models.CharField(choices=[('WINTER', 'Зима'), ('SPRING', 'Весна'), ('SUMMER', 'Літо'), ('FALL', 'Осінь')], default='SUMMER', max_length=255)),
                ('is_top', models.BooleanField(default=False)),
                ('background_image', models.ImageField(null=True, upload_to=apps.anime.s3_path.anime_background_image_save_path)),
                ('card_image', models.ImageField(null=True, upload_to=apps.anime.s3_path.anime_card_image_save_path)),
                ('year', models.SmallIntegerField()),
                ('average_time_episode', models.SmallIntegerField(blank=True, help_text='in minutes', null=True)),
                ('release_day_of_week', models.CharField(blank=True, choices=[('MONDAY', 'Понеділок'), ('TUESDAY', 'Вівторок'), ('WEDNESDAY', 'Середа'), ('THURSDAY', 'Четверг'), ('FRIDAY', "П'ятниця"), ('SATURDAY', 'Субота'), ('SUNDAY', 'Неділя')], null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date and time')),
                ('order', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('is_accessible', models.BooleanField(default=False)),
                ('start_opening', models.SmallIntegerField(blank=True, help_text='in seconds', null=True)),
                ('end_opening', models.SmallIntegerField(blank=True, help_text='in seconds', null=True)),
                ('start_ending', models.SmallIntegerField(blank=True, help_text='in seconds', null=True)),
                ('end_ending', models.SmallIntegerField(blank=True, help_text='in seconds', null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=apps.anime.s3_path.episode_preview_image_save_path)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('image', models.ImageField(null=True, upload_to=apps.anime.s3_path.anime_poster_image_save_path)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to=apps.anime.s3_path.anime_preview_image_save_path)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voiceover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date and time')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('type', models.CharField(choices=[('VOICEOVER', 'Озвучка'), ('SUBTITLES', 'Субтитри')], max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('WAIT', 'WAIT'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceoverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('event', models.CharField(choices=[('CREATED', 'Створено запит на додавання озвучки'), ('WAIT', 'Чекає на підтвердження'), ('CHANGED', 'Змінено'), ('DECLINED', 'Відхилено'), ('APPROVED', 'Підтвержено')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('WAIT', 'WAIT'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], max_length=100)),
            ],
            options={
                'verbose_name': 'Voiceover history',
                'verbose_name_plural': 'Voiceover history',
            },
        ),
    ]
