# Generated by Django 4.2.11 on 2024-09-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceoverhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voiceoverhistory',
            name='voiceover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceover_history', to='anime.voiceover'),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.episode'),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.group'),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previewimage',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AddField(
            model_name='poster',
            name='anime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AddField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AddField(
            model_name='episode',
            name='arch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.arch'),
        ),
        migrations.AddField(
            model_name='arch',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.director'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, to='anime.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='related',
            field=models.ManyToManyField(blank=True, to='anime.anime'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, to='anime.studio'),
        ),
        migrations.CreateModel(
            name='TOP100',
            fields=[
            ],
            options={
                'verbose_name': 'Top 100',
                'verbose_name_plural': 'Top 100',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('anime.anime',),
        ),
        migrations.AddIndex(
            model_name='voiceoverhistory',
            index=models.Index(fields=['event', 'voiceover_id'], name='anime_voice_event_7007f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('order', 'anime'), name='unique_episode_for_anime'),
        ),
        migrations.AddConstraint(
            model_name='arch',
            constraint=models.UniqueConstraint(fields=('order', 'anime'), name='unique_arch_for_anime'),
        ),
    ]
