# Generated by Django 4.2.11 on 2024-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceover',
            name='verified',
        ),
        migrations.AlterField(
            model_name='voiceoverhistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Створено запит на додавання озвучки'), ('WAIT', 'Чекає на підтвердження'), ('CHANGED', 'Змінено'), ('DECLINED', 'Відхилено'), ('APPROVED', 'Підтвержено'), ('COMMENT', 'Comment')], max_length=50),
        ),
    ]
