# Generated by Django 4.2.11 on 2024-04-22 11:33

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_episode_arch_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
