# Generated by Django 4.2.11 on 2024-09-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_voiceover_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='short_description',
            new_name='other_title',
        ),
    ]
