# Generated by Django 4.2.11 on 2024-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_studio_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('ANIME', 'ANIME'), ('MANGA', 'MANGA')], default='ANIME', max_length=255),
        ),
    ]
