# Generated by Django 4.2.11 on 2024-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(choices=[('WINTER', 'WINTER'), ('SPRING', 'SPRING'), ('SUMMER', 'SUMMER'), ('FALL', 'FALL')], default='SUMMER', max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(choices=[('G', 'All Ages'), ('PG', 'Children'), ('PG13', 'Teens 13 and Older'), ('R', '(violence & profanity)'), ('RPLUS', 'Profanity & Mild Nudity'), ('RX', 'Hentai')], max_length=255),
        ),
    ]
