# Generated by Django 4.2.11 on 2024-09-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_rename_short_description_anime_other_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='average_time_episode',
            field=models.PositiveSmallIntegerField(blank=True, help_text='in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='end_ending',
            field=models.PositiveSmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='end_opening',
            field=models.PositiveSmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='start_ending',
            field=models.PositiveSmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='start_opening',
            field=models.PositiveSmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
    ]
