# Generated by Django 4.2.11 on 2024-04-23 19:39

import apps.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to=apps.anime.models.anime_preview_image_save_path),
        ),
    ]
