# Generated by Django 4.2.11 on 2024-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_remove_voiceover_url_voiceover_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceover',
            name='file',
        ),
        migrations.AddField(
            model_name='voiceover',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
