# Generated by Django 4.2.11 on 2024-04-26 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0008_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceoverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('event', models.CharField(choices=[], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('WAIT', 'WAIT'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], max_length=100)),
            ],
            options={
                'verbose_name': 'Voiceover history',
                'verbose_name_plural': 'Voiceover history',
            },
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='short_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('WAIT', 'WAIT'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('is_main', 'anime_id'), name='unique_anime_image_anime_main_image'),
        ),
        migrations.AddField(
            model_name='voiceoverhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voiceoverhistory',
            name='voiceover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceover_history', to='anime.voiceover'),
        ),
        migrations.AddIndex(
            model_name='voiceoverhistory',
            index=models.Index(fields=['event', 'voiceover_id'], name='anime_voice_event_7007f6_idx'),
        ),
    ]
