# Generated by Django 4.2.11 on 2024-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_genre_name_alter_studio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, to='anime.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('CAME_OUT', 'CAME_OUT'), ('COMES_OUT', 'COMES_OUT'), ('ANNOUNCED', 'ANNOUNCED')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
