# Generated by Django 4.2.11 on 2024-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_alter_anime_genres_alter_anime_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
