# Generated by Django 4.2.11 on 2024-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_anime_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOP100',
            fields=[
            ],
            options={
                'verbose_name': 'Top 100',
                'verbose_name_plural': 'Top 100',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('anime.anime',),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
