# Generated by Django 4.2.11 on 2024-05-07 11:36

import apps.anime.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_top100_anime_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('image', models.ImageField(null=True, upload_to=apps.anime.models.anime_poster_image_save_path)),
                ('description', models.TextField(blank=True, default='')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
