# Generated by Django 4.2.11 on 2024-05-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='anime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
    ]
