# Generated by Django 4.2.11 on 2024-05-07 23:37

from django.db import migrations, models


def rename_anime_type(apps, schema_editor):
    Anime = apps.get_model('anime', 'Anime')
    Anime.objects.filter(type='MANGA').update(type='FILM')


def reverse_rename_anime_type(apps, schema_editor):
    Anime = apps.get_model('anime', 'Anime')
    Anime.objects.filter(type='FILM').update(type='MANGA')


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_poster_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('ANIME', 'ANIME'), ('FILM', 'FILM')], default='ANIME', max_length=255),
        ),
        migrations.RunPython(rename_anime_type, reverse_rename_anime_type)
    ]
