# Generated by Django 4.2.11 on 2024-05-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_alter_anime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(choices=[('WINTER', 'Зима'), ('SPRING', 'Весна'), ('SUMMER', 'Літо'), ('FALL', 'Осінь')], default='SUMMER', max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('CAME_OUT', 'Вийшов'), ('COMES_OUT', 'Виходить'), ('ANNOUNCED', 'Анонсовано')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('ANIME', 'Аніме'), ('FILM', 'Фільм')], default='ANIME', max_length=255),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='type',
            field=models.CharField(choices=[('VOICEOVER', 'Озвучка'), ('SUBTITLES', 'Субтитри')], max_length=255),
        ),
    ]
