# Generated by Django 4.2.11 on 2024-05-10 13:23

import apps.anime.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_alter_anime_season_alter_anime_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_main',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='PreviewImage',
        ),
        migrations.AddField(
            model_name='anime',
            name='background_image',
            field=models.ImageField(null=True, upload_to=apps.anime.models.anime_background_image_save_path),
        ),
        migrations.AddField(
            model_name='anime',
            name='card_image',
            field=models.ImageField(null=True, upload_to=apps.anime.models.anime_card_image_save_path),
        ),
    ]
