# Generated by Django 4.2.11 on 2024-05-13 16:29

from django.db import migrations, models


def rename_anime_type(apps, schema_editor):
    Anime = apps.get_model('anime', 'Anime')
    Anime.objects.filter(type='ANIME').update(type='ONA')


def reverse_rename_anime_type(apps, schema_editor):
    Anime = apps.get_model('anime', 'Anime')
    Anime.objects.filter(type='ONA').update(type='ANIME')


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_previewimage_anime_background_image_anime_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-order']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='previewimage',
                    name='unique_anime_image_anime_main_image',
                ),
            ]
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('SERIAL', 'Серіал'), ('FILM', 'Фільм'), ('ONA', 'ONA'), ('OVA', 'OVA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='voiceoverhistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Створено запит на додавання озвучки')], max_length=50),
        ),
        migrations.RunPython(rename_anime_type, reverse_rename_anime_type)
    ]
