# Generated by Django 4.2.11 on 2024-05-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceoverhistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Створено запит на додавання озвучки'), ('CHANGED', 'Змінено')], max_length=50),
        ),
    ]
