# Generated by Django 4.2.11 on 2024-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0020_alter_voiceoverhistory_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='average_time_episode',
            field=models.SmallIntegerField(blank=True, help_text='in minutes', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_day_of_week',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Понеділок'), ('TUESDAY', 'Вівторок'), ('WEDNESDAY', 'Середа'), ('THURSDAY', 'Четверг'), ('FRIDAY', "П'ятниця"), ('SATURDAY', 'Субота'), ('SUNDAY', 'Неділя')], null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='end_ending',
            field=models.SmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='end_opening',
            field=models.SmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='start_ending',
            field=models.SmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='start_opening',
            field=models.SmallIntegerField(blank=True, help_text='in seconds', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('CAME_OUT', 'Вийшов'), ('COMES_OUT', 'Виходить'), ('ANNOUNCED', 'Анонсовано')], default='ANNOUNCED', max_length=255),
        ),
    ]
