# Generated by Django 4.2.11 on 2024-06-11 12:10

import apps.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0021_anime_average_time_episode_anime_release_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='preview_image',
            field=models.ImageField(null=True, upload_to=apps.anime.models.episode_preview_image_save_path),
        ),
    ]
