# Generated by Django 4.2.11 on 2024-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0022_episode_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
