# Generated by Django 4.2.11 on 2024-06-12 13:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_alter_director_pseudonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='country',
        ),
        migrations.AddField(
            model_name='anime',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
