# Generated by Django 4.2.11 on 2024-07-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0024_remove_studio_country_anime_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, to='anime.studio'),
        ),
    ]
