# Generated by Django 4.2.11 on 2024-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0025_remove_anime_studio_anime_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='related',
        ),
        migrations.AddField(
            model_name='anime',
            name='related',
            field=models.ManyToManyField(blank=True, to='anime.anime'),
        ),
    ]
