# Generated by Django 4.2.11 on 2024-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_remove_anime_related_anime_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(choices=[('G', 'All Ages'), ('PG', 'Children'), ('PG13', 'Teens 13 and Older'), ('R', '(violence & profanity)'), ('RPLUS', 'Profanity & Mild Nudity')], max_length=255),
        ),
        migrations.AlterField(
            model_name='director',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
