# Generated by Django 4.2.11 on 2024-08-08 15:01

import apps.anime.s3_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0027_alter_anime_rating_alter_director_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.director'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.SmallIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.anime.s3_path.episode_preview_image_save_path),
        ),
    ]
