# Generated by Django 4.2.11 on 2024-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0028_remove_anime_rank_remove_episode_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceoverhistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Створено запит на додавання озвучки'), ('WAIT', 'Чекає на підтвердження'), ('CHANGED', 'Змінено'), ('DECLINED', 'Відхилено'), ('APPROVED', 'Підтвержено')], max_length=50),
        ),
    ]
