# Generated by Django 4.2.11 on 2024-08-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0029_alter_voiceoverhistory_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='pseudonym',
        ),
    ]
