# Generated by Django 4.2.11 on 2024-08-12 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0030_remove_director_pseudonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
