# Generated by Django 4.2.11 on 2024-08-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0031_alter_anime_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParseAnimeLog',
        ),
    ]
