# Generated by Django 4.2.11 on 2024-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimelisttoken',
            name='redirect_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='myanimelisttoken',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myanimelisttoken',
            name='code_challenge',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myanimelisttoken',
            name='code_verifier',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myanimelisttoken',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
    ]
