# Generated by Django 4.2.11 on 2024-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0002_myanimelisttoken_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimelisttoken',
            name='expires_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myanimelisttoken',
            name='token_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
