# Generated by Django 4.2.11 on 2024-06-25 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0003_myanimelisttoken_expires_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myanimelisttoken',
            old_name='redirect_url',
            new_name='authorisation_url',
        ),
        migrations.RemoveField(
            model_name='myanimelisttoken',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='myanimelisttoken',
            name='expired_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myanimelisttoken',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date and time'),
        ),
    ]
