# Generated by Django 4.2.11 on 2024-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0004_rename_redirect_url_myanimelisttoken_authorisation_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updaterelease',
            name='response_status',
        ),
        migrations.AddField(
            model_name='updaterelease',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
