# Generated by Django 4.2.11 on 2024-06-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0005_remove_updaterelease_response_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimelisttoken',
            name='authorisation_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
