# Generated by Django 4.2.11 on 2024-07-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0006_alter_myanimelisttoken_authorisation_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyAnimeListToken',
            new_name='SourceAnimeListToken',
        ),
    ]
