# Generated by Django 4.2.11 on 2024-08-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_release', '0007_rename_myanimelisttoken_sourceanimelisttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceAnimeListToken',
        ),
        migrations.DeleteModel(
            name='UpdateRelease',
        ),
    ]
