# Generated by Django 4.2.11 on 2024-09-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpAppealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('event', models.CharField(choices=[('ASSIGNED', 'Тікет був пизначений'), ('UNASSIGNED', 'Тікет позбувся пизначення'), ('IN_PROGRESS', 'Тікет в процесі'), ('RESOLVED', 'Тікет був вирішений'), ('OPEN', 'Тікет відкритий'), ('COMMENT', 'Comment')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightholderAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('release_url', models.TextField()),
                ('document_url', models.TextField()),
                ('explanation', models.TextField()),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightholderAppealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('event', models.CharField(choices=[('ASSIGNED', 'Тікет був пизначений'), ('UNASSIGNED', 'Тікет позбувся пизначення'), ('IN_PROGRESS', 'Тікет в процесі'), ('RESOLVED', 'Тікет був вирішений'), ('OPEN', 'Тікет відкритий'), ('COMMENT', 'Comment')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=100)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rightholderappeal_history', to='support.rightholderappeal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
