# Generated by Django 4.2.11 on 2024-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_helpappeal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightholderappeal',
            name='title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rightholderappeal',
            name='document_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rightholderappeal',
            name='release_url',
            field=models.TextField(),
        ),
    ]
