@startuml

package user {
	object _user
		_user : id
		_user : username
		_user : email
		_user : password
		_user : is_subscribed
		_user : avatar file
		_user : status
		_user : last seen

	object _team
		_team : id
		_team : name
		_team : logo
		_team : background
		_team : description
		_team : telegram
		_team : email
		_team : is_verified
		_team : other sites ...

	object _user_team
		_user_team : id
		_user_team : user_id
		_user_team : team_id

	object _user_anime
		_user_anime : manga_id
		_user_anime : user_id
		_user_anime : type (тип улюблене|преглянуте|...)

}

package support {
	object _helpdesk
		_helpdesk : id
		_helpdesk : type (типи звернень)
		_helpdesk : user_id
		_helpdesk : email
		_helpdesk : text

	object _complaints
		_complaints : id
		_complaints : user_id
		_complaints : name organization
		_complaints : contact person
		_complaints : email
		_complaints : explanation text (Текст-пояснення, який ви хотіли залишити в оголошенні факту видалення публікації)
		_complaints : content (Прямі посилання на сторінки ресурсу, інформація з яких потребує видалення)
		_complaints : document (Посилання на документ, який є доказом наявності у Вас прав на матеріал, розміщений на сайті)
		_complaints : comment
}

package manga {

	object _manga
		_manga : id
		_manga : title
		_manga : created
		_manga : updated
		_manga : start_date
		_manga : end_date
		_manga : rank
		_manga : short_description
		_manga : description
		_manga : like (список користуваців)
		_manga : dislike (список користуваців)
		_manga : status
		_manga : country
		_manga : director_id
		_manga : slug (коротка назва для створення урла)
		_manga : url (для MyAnimeList)
		_manga : type (фільм, серіал)
		_manga : age_rating
		_manga : year
		_manga : viewed (скільки переглянуто)
		_manga : studio_id
		_manga : season (літо|осінь|...)
		_manga : card_image
		_manga : is_top
		_manga : is_top
		_manga : genres
		_manga : average_time_episode
		_manga : release_day_of_week

	object _episode
		_episode : id
		_episode : title
		_episode : anime
		_episode : status
		_episode : is_accessible
		_episode : start_opening
		_episode : end_opening
		_episode : start_ending
		_episode : end_ending
		_episode : youtube_url
		_episode : preview_image
		_episode : created
		_episode : updated
		_episode : order (номер серії)

	object _arch
		_arch : title
		_arch : anime_id
		_arch : order (номер серії)

	object _voiceover
		_voiceover : id
		_voiceover : team_id
		_voiceover : user_id
		_voiceover : episode_id
		_voiceover : url
		_voiceover : status
		_voiceover : created
		_voiceover : type (озвучка|субтитри)

	object _manga_genres
		_manga_genres : id
		_manga_genres : manga_id
		_manga_genres : genre_id

	object _genre
		_genre : id
		_genre : name

	object _studio
		_studio : id
		_studio : description
		_studio : name

	object _director
		_director : id
		_director : first_name
		_director : last_name
		_director : pseudonym
		_director : url

	object _preview_image
		_preview_image : id
		_preview_image : anime
		_preview_image : file

	object _poster
		_poster : id
		_poster : anime
		_poster : image
		_poster : description
		_poster : created
}

_helpdesk }|--|| _user
_complaints }|--|| _user

_team ||--|| _user_team
_user ||--|| _user_team

_arch }|--|| _manga

_episode }|--|| _manga
_studio ||--|| _manga
_director ||--|| _manga
_manga_genres ||--|| _manga
_manga_genres ||--|| _genre

_preview_image }|--|| _episode

_voiceover }|--|| _episode
_voiceover ||--|| _team
_voiceover ||--|| _user

_poster }|--|| _manga

_user ||--|{ _user_anime

@enduml