name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: "Builds and publishes a docker image"
    runs-on: ubuntu-latest
    environment: "DEV"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can be deployed.
          make write-versions-file
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)